name: "🔨 Chore (기타 작업)"
description: "패키지 매니저 수정, 설정 변경 등 기타 작업을 위해 사용합니다."
title: "🔨 Chore: "
labels: ["🔨 Chore (기타 작업)"]
type: Task
body:
  - type: textarea
    id: overview
    attributes:
      label: "🛠️ Issue Overview"
      placeholder: "예: 패키지 의존성 버전 업데이트"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "📝 Issue Description"
      placeholder: "예: 보안 취약점이 발견된 axios 버전을 최신으로 업데이트하고 빌드 정상 여부 확인"
  - type: textarea
    id: todo
    attributes:
      label: "✅ To do"
      placeholder: "예: - [ ] package.json 버전 수정\n- [ ] npm install 및 빌드 테스트"