name: "♻️ Refactor (리팩토링)"
description: "코드 구조 개선 및 성능 최적화를 위해 사용합니다."
title: "♻️ Refactor: "
labels: ["♻️ Refactor (리팩토링)"]
type: Task
body:
  - type: textarea
    id: overview
    attributes:
      label: "🛠️ Issue Overview"
      placeholder: "예: 반복되는 API 호출 로직 Custom Hook화"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "📝 Issue Description"
      placeholder: "예: 컴포넌트 내부에 흩어진 fetch 로직을 useGetTravelList 훅으로 통합"
  - type: textarea
    id: todo
    attributes:
      label: "✅ To do"
      placeholder: "예: - [ ] 비즈니스 로직 분리 및 컴포넌트 경량화"